apiVersion: v1
kind: ServiceAccount
metadata:
  name: runner
  namespace: prompp-bench
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: runner
  namespace: prompp-bench
rules:
  - apiGroups: [""]
    resources: ["pods", "persistentvolumeclaims", "services"]
    verbs: ["get", "list", "watch", "create", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch", "create", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: runner
  namespace: prompp-bench
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: runner
subjects:
  - kind: ServiceAccount
    name: runner
    namespace: prompp-bench
